In [1]:
import pandas as pd
import numpy as np
import math
import warnings
warnings.filterwarnings('ignore')

In [9]:
df_placar2 = pd.read_csv("vlr_placar2.csv")
df_placar2

,URL,Mapa,Time1,Mapas_T1,Score_T1,Time2,Mapas_T2,Score_T2,Vencedor
0,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,Haven,LOUD,NaN,7,Cloud9,NaN,13,Cloud9
1,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,Abyss,LOUD,NaN,11,Cloud9,NaN,13,Cloud9
2,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,AllMaps,LOUD,0.0,18,Cloud9,2.0,26,Cloud9
3,https://www.vlr.gg/596399/envy-vs-evil-geniuse...,Abyss,ENVY,NaN,9,Evil Geniuses,NaN,13,Evil Geniuses
4,https://www.vlr.gg/596399/envy-vs-evil-geniuse...,Corrode,ENVY,NaN,13,Evil Geniuses,NaN,10,ENVY
...,...,...,...,...,...,...,...,...,...
1567,https://www.vlr.gg/189059/evil-geniuses-vs-nrg...,AllMaps,Evil Geniuses,1.0,35,NRG,3.0,50,NRG
1568,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,Ascent,LOUD,NaN,13,NRG,NaN,9,LOUD
1569,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,Bind,LOUD,NaN,13,NRG,NaN,11,LOUD
1570,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,Fracture,LOUD,NaN,13,NRG,NaN,11,LOUD
1571,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,AllMaps,LOUD,3.0,39,NRG,0.0,31,LOUD

In [10]:
df_stats2 = pd.read_csv("vlr_stats2.csv")
df_stats2

,URL,Mapa_Num,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD
0,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,70.0,166.0,30.0,2.0,1.0,1.0
1,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,2,75.0,152.0,26.0,0.0,1.0,-1.0
2,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,-2,55.0,102.0,35.0,2.0,3.0,-1.0
3,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,-2,65.0,99.0,27.0,0.0,3.0,-3.0
4,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,-3,60.0,125.0,35.0,4.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10896,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,11,2,79.0,145.0,32.0,0.0,3.0,-3.0
10897,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,12,1,75.0,155.0,24.0,2.0,1.0,1.0
10898,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,1,-1,67.0,110.0,15.0,2.0,2.0,0.0
10899,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,4,-4,71.0,141.0,15.0,6.0,3.0,3.0
10900,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,10,-9,54.0,95.0,16.0,2.0,3.0,-1.0

# Tratamento de Dados Duplicados

In [11]:
df_stats2 = pd.read_csv("vlr_stats2.csv")
df_stats2


chave = ['URL', 'Jogador', 'Mapa_Num']

dups = df_stats2[df_stats2.duplicated(subset=chave, keep=False)]
print(f"Linhas duplicadas: {len(dups)}")
print(f"Combinações únicas duplicadas: {dups.groupby(chave).ngroups}")
display(dups.sort_values(chave))


df_stats2 = df_stats2.drop_duplicates(subset=chave, keep='first').reset_index(drop=True)
print(f"\nShape final: {df_stats2.shape}")

Linhas duplicadas: 0
Combinações únicas duplicadas: 0

Empty DataFrame
Columns: [URL, Mapa_Num, Mapa, Jogador, Time, Agente, R, ACS, K, D, A, +/-, KAST, ADR, HS%, FK, FD, +/-_FK_FD]
Index: []

Shape final: (10901, 18)

In [12]:
df_stats2.to_csv("vlr_stats2.csv", index=False)
df_stats2

,URL,Mapa_Num,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD
0,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,70.0,166.0,30.0,2.0,1.0,1.0
1,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,2,75.0,152.0,26.0,0.0,1.0,-1.0
2,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,-2,55.0,102.0,35.0,2.0,3.0,-1.0
3,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,-2,65.0,99.0,27.0,0.0,3.0,-3.0
4,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,-3,60.0,125.0,35.0,4.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10896,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,11,2,79.0,145.0,32.0,0.0,3.0,-3.0
10897,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,12,1,75.0,155.0,24.0,2.0,1.0,1.0
10898,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,1,-1,67.0,110.0,15.0,2.0,2.0,0.0
10899,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,4,-4,71.0,141.0,15.0,6.0,3.0,3.0
10900,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,10,-9,54.0,95.0,16.0,2.0,3.0,-1.0

# Juntas os DF's Placar e Stats

In [40]:
df_merged = df_stats2.merge(
    df_placar2,
    left_on=['URL', 'Mapa'],
    right_on=['URL', 'Mapa'],
    how='left'
).query("Mapa != 'AllMaps'")

nome_para_tag = {
    'Sentinels': 'SEN',
    'NRG': 'NRG',
    'Cloud9': 'C9',
    'FURIA': 'FUR',
    'LEVIATÁN': 'LEV',
    'Evil Geniuses': 'EG',
    '100 Thieves': '100T',
    'KRÜ Esports': 'KRU',
    'VISA KRÜ(KRÜ Esports)': 'KRU',
    'G2 Esports': 'G2',
    'ENVY': 'ENVY',
    'MIBR': 'MIBR',
    'LOUD': 'LOUD',
    '2Game Esports': '2G'
}

for col in ['Time', 'Time1', 'Time2', 'Vencedor']:
    df_merged[col] = df_merged[col].map(nome_para_tag).fillna(df_merged[col])


df_merged['Vencedor'] = (df_merged['Vencedor'] == df_merged['Time']).astype(int)

df_merged.drop(columns=['URL','Mapa_Num','Time1','Time2','Mapas_T1', 'Mapas_T2', 'Score_T1','Score_T2'], inplace=True)
df_merged.rename(columns={'Vencedor': 'target'}, inplace=True)

#df_merged.to_csv("status_individual.csv", index=False)
df_merged

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,target
0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,70.0,166.0,30.0,2.0,1.0,1.0,0
1,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,2,75.0,152.0,26.0,0.0,1.0,-1.0,0
2,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,-2,55.0,102.0,35.0,2.0,3.0,-1.0,0
3,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,-2,65.0,99.0,27.0,0.0,3.0,-3.0,0
4,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,-3,60.0,125.0,35.0,4.0,4.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10896,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,11,2,79.0,145.0,32.0,0.0,3.0,-3.0,0
10897,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,12,1,75.0,155.0,24.0,2.0,1.0,1.0,0
10898,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,1,-1,67.0,110.0,15.0,2.0,2.0,0.0,0
10899,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,4,-4,71.0,141.0,15.0,6.0,3.0,3.0,0
10900,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,10,-9,54.0,95.0,16.0,2.0,3.0,-1.0,0

# Descobrir as Features mais importantes para um time ganhar

In [155]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

df_merged = pd.read_csv("merged_status_placar.csv")
df = df_merged.copy()
df['Win'] = (df['Time'] == df['Vencedor']).astype(int)
cols_drop = [
    'Mapa',
    'Time',
    'Agente',
    'Vencedor',
    'Adversario',
    'Score_Time',
    'Score_Adv',
    'Mapas_Time',
    'Mapas_Adv',
    'URL',
    'Jogador'
]

df_model = df.drop(columns=cols_drop)

X = df_model.drop(columns=['Win'])
y = df_model['Win']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

importances = model.feature_importances_

feat_importance = pd.Series(importances, index=X.columns)
feat_importance = feat_importance.sort_values(ascending=False)

print(feat_importance.head(20))

+/-          0.142999
KAST         0.121974
D            0.116403
R            0.103842
ACS          0.093438
ADR          0.082862
HS%          0.068935
A            0.066584
K            0.064496
+/-_FK_FD    0.042758
FD           0.037090
FK           0.034781
Mapa_Num     0.023839
dtype: float64

# Calculo de Impacto do Jogador por Cada Partida

In [41]:
df_merged2 = df_stats2.merge(
    df_placar2,
    left_on=['URL', 'Mapa'],
    right_on=['URL', 'Mapa'],
    how='left'
).query("Mapa != 'AllMaps'")

nome_para_tag = {
    'Sentinels': 'SEN',
    'NRG': 'NRG',
    'Cloud9': 'C9',
    'FURIA': 'FUR',
    'LEVIATÁN': 'LEV',
    'Evil Geniuses': 'EG',
    '100 Thieves': '100T',
    'KRÜ Esports': 'KRU',
    'VISA KRÜ(KRÜ Esports)': 'KRU',
    'G2 Esports': 'G2',
    'ENVY': 'ENVY',
    'MIBR': 'MIBR',
    'LOUD': 'LOUD',
    '2Game Esports': '2G'
}

for col in ['Time', 'Time1', 'Time2', 'Vencedor']:
    df_merged2[col] = df_merged2[col].map(nome_para_tag).fillna(df_merged2[col])


df_merged2['Vencedor'] = (df_merged2['Vencedor'] == df_merged2['Time']).astype(int)

df_merged2.rename(columns={'Vencedor': 'target'}, inplace=True)

df_merged2

,URL,Mapa_Num,Mapa,Jogador,Time,Agente,R,ACS,K,D,...,FK,FD,+/-_FK_FD,Time1,Mapas_T1,Score_T1,Time2,Mapas_T2,Score_T2,target
0,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,...,2.0,1.0,1.0,LOUD,NaN,7,C9,NaN,13,0
1,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,...,0.0,1.0,-1.0,LOUD,NaN,7,C9,NaN,13,0
2,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,...,2.0,3.0,-1.0,LOUD,NaN,7,C9,NaN,13,0
3,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,...,0.0,3.0,-3.0,LOUD,NaN,7,C9,NaN,13,0
4,https://www.vlr.gg/596398/loud-vs-cloud9-vct-2...,0,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,...,4.0,4.0,0.0,LOUD,NaN,7,C9,NaN,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10896,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,crashies,NRG,Skye,1.24,212.0,19,17,...,0.0,3.0,-3.0,LOUD,NaN,13,NRG,NaN,11,0
10897,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,s0m,NRG,Brimstone,1.24,240.0,19,18,...,2.0,1.0,1.0,LOUD,NaN,13,NRG,NaN,11,0
10898,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,Victor,NRG,Killjoy,0.83,168.0,16,17,...,2.0,2.0,0.0,LOUD,NaN,13,NRG,NaN,11,0
10899,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,ardiis,NRG,Jett,0.81,210.0,15,19,...,6.0,3.0,3.0,LOUD,NaN,13,NRG,NaN,11,0
10900,https://www.vlr.gg/189055/loud-vs-nrg-esports-...,3,Fracture,FiNESSE,NRG,Breach,0.65,136.0,10,19,...,2.0,3.0,-1.0,LOUD,NaN,13,NRG,NaN,11,0

In [11]:
df_merged2.describe()

,Mapa_Num,R,ACS,K,D,A,+/-,KAST,ADR,HS%,FK,FD,+/-_FK_FD,Mapas_T1,Score_T1,Mapas_T2,Score_T2,target
count,11240.000000,11230.000000,11230.000000,11240.000000,11240.000000,11240.00000,11240.000000,11230.000000,11230.000000,11230.000000,11230.000000,11230.000000,11230.000000,0.0,11240.000000,0.0,11240.000000,11240.000000
mean,1.438612,0.997397,196.414693,14.570196,14.585587,6.12589,-0.015391,72.002315,128.978094,27.367676,2.114515,2.114515,0.000000,NaN,10.695730,NaN,10.458185,0.462189
std,1.263688,0.332194,56.939685,5.242806,3.591243,3.67155,5.954407,11.651162,36.099935,9.622128,1.787508,1.679258,2.113445,NaN,3.348004,NaN,3.588277,0.498590
min,0.000000,0.010000,27.000000,1.000000,3.000000,0.00000,-18.000000,21.000000,19.000000,0.000000,0.000000,0.000000,-9.000000,NaN,0.000000,NaN,1.000000,0.000000
25%,0.000000,0.770000,157.000000,11.000000,13.000000,3.00000,-4.000000,65.000000,104.000000,21.000000,1.000000,1.000000,-1.000000,NaN,8.000000,NaN,8.000000,0.000000
50%,2.000000,0.980000,193.000000,14.000000,15.000000,6.00000,0.000000,73.000000,127.000000,26.000000,2.000000,2.000000,0.000000,NaN,13.000000,NaN,13.000000,0.000000
75%,2.000000,1.210000,232.000000,18.000000,17.000000,8.00000,4.000000,80.000000,151.000000,33.000000,3.000000,3.000000,1.000000,NaN,13.000000,NaN,13.000000,1.000000
max,5.000000,2.490000,460.000000,47.000000,32.000000,25.00000,28.000000,100.000000,294.000000,80.000000,12.000000,12.000000,9.000000,NaN,20.000000,NaN,21.000000,1.000000

In [42]:
REF_MEDIANO = {
    'Mapa_Num':   2.0,
    'R':          0.98,
    'ACS':        193.0,
    'K':          14.0,
    'D':          15.0,
    'A':          6.0,
    '+/-':        0.0,
    'KAST':       73.0,
    'ADR':        127.0,
    'HS':        26.0,
    'FK':         2.0,
    'FD':         2.0,
    '+/-_FK_FD':  0.0,
    'Score_T1':   13.0,
    'Score_T2':   13.0
}

PESOS = {
    '+/-':        0.143,
    'KAST':       0.122,
    'D':          0.116,
    'R':          0.104,
    'ACS':        0.093,
    'ADR':        0.083,
    'HS':        0.069,
    'A':          0.067,
    'K':          0.064,
    '+/-_FK_FD':  0.043,
    'FD':         0.037,
    'FK':         0.035,
    'Mapa_Num':   0.024
}


def calcular_impacto(r, acs, kast, adr, hs, tot_k, tot_d, tot_fk, tot_fd, jogos):
    def clip(x, min_v=0.5, max_v=1.5):
        return max(min(x, max_v), min_v)

    kd_rate  = (tot_k - tot_d) / jogos if jogos > 0 else 0
    fkd_rate = (tot_fk - tot_fd) / jogos if jogos > 0 else 0

    scores = {
        'R':          clip(r    / REF_MEDIANO['R']),
        'ACS':        clip(acs  / REF_MEDIANO['ACS']),
        'ADR':        clip(adr  / REF_MEDIANO['ADR']),
        'KAST':       clip(kast / REF_MEDIANO['KAST']),
        'HS':         clip(math.sqrt(hs / REF_MEDIANO['HS'])),
        '+/-':        clip(1 + (kd_rate  / 2)),
        '+/-_FK_FD':  clip(1 + (fkd_rate / 1)),
    }

    score = sum(PESOS[m] * scores[m] for m in scores)
    return round(score, 3)


def calcular_impacto_por_mapa(df: pd.DataFrame) -> pd.DataFrame:
    
    colunas_numericas = ['R', 'ACS', 'KAST', 'ADR', 'HS%', 'K', 'D', 'FK', 'FD']
    df = df.copy()
    for col in colunas_numericas:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    def calcular_linha(row):
        return calcular_impacto(
            r      = row['R'],
            acs    = row['ACS'],
            kast   = row['KAST'],
            adr    = row['ADR'],
            hs     = row['HS%'],
            tot_k  = row['K'],
            tot_d  = row['D'],
            tot_fk = row['FK'],
            tot_fd = row['FD'],
            jogos  = 1          
        )

    df['Impacto'] = df.apply(calcular_linha, axis=1)

    colunas_id = ['URL', 'Mapa_Num', 'Mapa', 'Jogador', 'Time', 'Agente']
    colunas_existentes = [c for c in colunas_id if c in df.columns]
    demais = [c for c in df.columns if c not in colunas_existentes and c != 'Impacto']

    df = df[colunas_existentes + demais + ['Impacto']]

    return df


df_impacto = calcular_impacto_por_mapa(df_merged2)
df_impacto.drop(columns=['URL','Mapa_Num','Mapas_T1', 'Mapas_T2'], inplace=True)

df_impacto.to_csv("df_impacto_cada_mapa.csv", index=False)

df_impacto.head(5)

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,HS%,FK,FD,+/-_FK_FD,Time1,Score_T1,Time2,Score_T2,target,Impacto
0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,...,30.0,2.0,1.0,1.0,LOUD,7,C9,13,0,0.821
1,Haven,cauanzin,LOUD,Sova,0.98,209.0,15,13,3,2,...,26.0,0.0,1.0,-1.0,LOUD,7,C9,13,0,0.734
2,Haven,Virtyy,LOUD,Yoru,0.70,178.0,14,16,4,-2,...,35.0,2.0,3.0,-1.0,LOUD,7,C9,13,0,0.492
3,Haven,pANcada,LOUD,Omen,0.67,145.0,11,13,1,-2,...,27.0,0.0,3.0,-3.0,LOUD,7,C9,13,0,0.478
4,Haven,lukxo,LOUD,Killjoy,0.65,192.0,13,16,3,-3,...,35.0,4.0,4.0,0.0,LOUD,7,C9,13,0,0.538

In [13]:
df_impacto[df_impacto['Jogador'] == 'Darker']

,Mapa,Jogador,Time,Agente,R,ACS,K,D,A,+/-,...,HS%,FK,FD,+/-_FK_FD,Time1,Score_T1,Time2,Score_T2,target,Impacto
0,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,...,30.0,2.0,1.0,1.0,LOUD,7,C9,13,0,0.821
1,Haven,Darker,LOUD,Viper,1.12,256.0,18,16,6,2,...,30.0,2.0,1.0,1.0,LOUD,7,C9,13,0,0.821
42,Abyss,Darker,LOUD,Astra,0.95,166.0,15,16,8,-1,...,31.0,1.0,3.0,-2.0,LOUD,11,C9,13,0,0.540
43,Abyss,Darker,LOUD,Astra,0.95,166.0,15,16,8,-1,...,31.0,1.0,3.0,-2.0,LOUD,11,C9,13,0,0.540
564,Breeze,Darker,LOUD,Kayo,1.06,187.0,16,16,5,0,...,18.0,2.0,3.0,-1.0,LOUD,13,100T,11,1,0.634
565,Breeze,Darker,LOUD,Kayo,1.06,187.0,16,16,5,0,...,18.0,2.0,3.0,-1.0,LOUD,13,100T,11,1,0.634
608,Bind,Darker,LOUD,Tejo,0.54,157.0,10,17,3,-7,...,29.0,3.0,3.0,0.0,LOUD,6,100T,13,0,0.477
609,Bind,Darker,LOUD,Tejo,0.54,157.0,10,17,3,-7,...,29.0,3.0,3.0,0.0,LOUD,6,100T,13,0,0.477
628,Pearl,Darker,LOUD,Tejo,0.32,71.0,3,13,3,-10,...,6.0,1.0,0.0,1.0,LOUD,2,100T,13,0,0.422
629,Pearl,Darker,LOUD,Tejo,0.32,71.0,3,13,3,-10,...,6.0,1.0,0.0,1.0,LOUD,2,100T,13,0,0.422
1140,Haven,Darker,LOUD,Viper,1.20,288.0,18,15,4,3,...,29.0,3.0,2.0,1.0,LOUD,5,EG,13,0,0.857
1141,Haven,Darker,LOUD,Viper,1.20,288.0,18,15,4,3,...,29.0,3.0,2.0,1.0,LOUD,5,EG,13,0,0.857
1184,Abyss,Darker,LOUD,Kayo,1.01,193.0,18,19,13,-1,...,18.0,2.0,1.0,1.0,LOUD,12,EG,14,0,0.576
1185,Abyss,Darker,LOUD,Kayo,1.01,193.0,18,19,13,-1,...,18.0,2.0,1.0,1.0,LOUD,12,EG,14,0,0.576
9596,Lotus,Darker,LOUD,Vyse,1.29,294.0,22,19,4,3,...,19.0,2.0,0.0,2.0,ENVY,13,LOUD,9,0,0.825
9615,Pearl,Darker,LOUD,Astra,1.61,310.0,28,15,9,13,...,32.0,2.0,1.0,1.0,ENVY,11,LOUD,13,1,0.936
9626,Breeze,Darker,LOUD,Astra,1.62,308.0,25,12,10,13,...,24.0,4.0,2.0,2.0,ENVY,8,LOUD,13,1,0.889
9749,Haven,Darker,LOUD,Viper,0.55,151.0,10,18,6,-8,...,29.0,0.0,3.0,-3.0,MIBR,13,LOUD,10,0,0.456
9769,Split,Darker,LOUD,Cypher,0.37,88.0,3,14,4,-11,...,20.0,2.0,2.0,0.0,MIBR,13,LOUD,4,0,0.398
9809,Haven,Darker,LOUD,Viper,0.56,156.0,11,19,5,-8,...,32.0,1.0,3.0,-2.0,G2,13,LOUD,9,0,0.484
9826,Pearl,Darker,LOUD,Astra,1.03,203.0,15,17,13,-2,...,24.0,2.0,1.0,1.0,G2,13,LOUD,10,0,0.623
9893,Lotus,Darker,LOUD,Vyse,1.15,242.0,13,9,4,4,...,36.0,2.0,1.0,1.0,LOUD,13,C9,1,1,0.849
9912,Split,Darker,LOUD,Vyse,0.97,227.0,16,18,5,-2,...,23.0,1.0,1.0,0.0,LOUD,8,C9,13,0,0.617
9923,Breeze,Darker,LOUD,Astra,0.73,145.0,10,17,9,-7,...,32.0,1.0,0.0,1.0,LOUD,13,C9,11,1,0.576
10020,Bind,Darker,LOUD,Viper,1.24,238.0,12,14,6,-2,...,27.0,2.0,0.0,2.0,LOUD,3,LEV,13,0,0.693
10043,Breeze,Darker,LOUD,Kayo,0.94,166.0,16,16,5,0,...,23.0,1.0,5.0,-4.0,LOUD,14,LEV,12,1,0.618
10051,Haven,Darker,LOUD,Phoenix,1.27,259.0,22,18,8,4,...,22.0,1.0,1.0,0.0,LOUD,13,LEV,10,1,0.795